"""
Plane Jacobian campaign - Session 36, WP-1
THE T5-T8 GATE: T6 AND T8 ARE REFUTED ON ALPOGE'S MAP.

The Session-36 handoff proposed four lemmas T5-T8 about the monodromy of a
Keller counterexample, all tagged [DERIVED] and unverified, and made WP-2
(the congruence d = chi mod 3), part of WP-5, and WP-6 depend on them.  The
handoff's own instruction:

    "If r = 1 on Alpoge's map, T8 is false and F5 collapses - report
     immediately."

r = 1 on Alpoge's map.  T8 is false.  T6 is false.  Reported here.

=====================================================================
THE TEST OBJECT
=====================================================================

Alpoge's dimension-3 counterexample (July 2026) is the only known live
example of an etale non-injective polynomial map, i.e. exactly the object
T5-T8 describe and which conjecturally does not exist in the plane.
T5, T6, T8 are dimension-independent, so it is a legitimate test bed.

    P = (1+xy)^3 z + y^2 (1+xy)(4+3xy)
    Q = y + 3x(1+xy)^2 z + 3x y^2 (4+3xy)
    R = 2x - 3x^2 y - x^3 z

Verified below: det JF = -2 identically, and the three distinct points
(0,0,-1/4), (1,-3/2,13/2), (-1,3/2,13/2) share the image (-1/4,0,0).

=====================================================================
RESULT 1  the geometric degree is 3
=====================================================================

vdim of (P-a, Q-b, R-c) over Q(a,b,c) is 3, and generic rational fibres
have exactly 3 points.  Consistent with the 3-point collision.

=====================================================================
RESULT 2  the non-properness set is IRREDUCIBLE: r = 1, nu = 2
=====================================================================

The containment used is sound and it is what makes the census exhaustive:
if G is a Groebner basis of (P-a,Q-b,R-c) over Q(a,b,c) with leading
coefficients l_1..l_k, then at any target where every l_i is nonzero the
specialised basis is still a Groebner basis, so the fibre count is d.
Hence

    S_F  is contained in  V(l_1 * ... * l_k),

and since S_F is pure of codimension 1 (Jelonek), every component of S_F
IS one of the irreducible factors of the l_i.  Factoring gives exactly
five candidate surfaces:

    C1  9abc - 4b^2 + 18a
    C2  9ac - b
    C3  b^3 c + 27a^2 c^2 - 18abc - b^2 + 16a
    C4  3b^2 c^2 + 36ac^2 - 20bc + 16
    C5  the irreducible factor of the fourth leading coefficient

Fibre counts at rational points of each (Singular vdim, exact):

    C1  3 3 3 3 3 3     not in S_F
    C2  3 3 3 3 3 3     not in S_F
    C3  1 1 1 1 1 1     IN S_F, nu = d - 1 = 2
    C4  3 3 3 3 3       not in S_F
    C5  3 3 3 3         not in S_F  (its one dropping point lies on C3)

Since F is etale every fibre is REDUCED, so a drop in cardinality is
always an escape to infinity and never a collision.  The count is
therefore exactly the Jelonek multiplicity.

    r = 1,   nu_1 = 2,   d = 3.

=====================================================================
RESULT 3  T6 and T8 are REFUTED
=====================================================================

T6 (transitivity budget) claimed  sum_i (nu_i - 1) >= d - 1.
Here: 2 - 1 = 1, and d - 1 = 2.   1 >= 2 is FALSE.

T8 (r >= 2) claimed the non-properness set has at least two components.
Here r = 1.  FALSE.  T8's proof invoked T6, so it falls with it.

WHERE THE ARGUMENT BREAKS, precisely.  T6 counted one generator per
component of S_F.  But pi_1 of the complement of an irreducible
hypersurface is generated by the meridian AND ALL ITS CONJUGATES, which
are in general several distinct permutations, each moving at most nu
sheets but not the same nu sheets.  Two conjugate transpositions (12) and
(13) generate S_3 and act transitively on 3 sheets - which is exactly what
happens here.  A single component with nu = 2 is therefore perfectly
capable of supporting transitive monodromy on 3 sheets.  H_1 is abelian
and would have forced the budget; pi_1 is not, and does not.

This is not a defect of the test object.  It is a defect of the argument,
and it would have propagated into WP-2's congruence unchecked.

=====================================================================
SCOPE - what is and is not refuted
=====================================================================

REFUTED: T6, T8.
NOT TESTED HERE: T5 (meridian support) and T7 (the line-slice identity).
T5 is about a single meridian and is untouched by the above.  T7 is an
Euler-characteristic count of a different character; it was not tested,
so it remains [DERIVED] and unverified.

Since F5 (the congruence d = chi mod 3) rests on T7, and T7 is unverified
while its stablemates T6 and T8 are now false, WP-2 must NOT be run on the
strength of this family.  Per the handoff's own decision tree, this sends
the session to WP-3.

=====================================================================
A TOOLING BUG FOUND AND RECORDED
=====================================================================

The first pass computed fibre counts in sympy with the campaign's existing
standard-monomial helper, and got 12 for every generic fibre where
Singular's vdim gives 3.  Cause: the helper takes the leading monomial as
Poly(g, x, y, z).monoms()[0], which is the LEX-largest monomial, not the
leading monomial of the grevlex basis the Groebner call produced.  In two
variables the two happened to coincide on every case the campaign ran, so
the bug was invisible in Sessions 33-34; in three variables it is not.

All fibre counts here are Singular vdim.  Added to the silent-lie table.
"""

import os
import re
import subprocess
import tempfile

from sympy import Matrix, Rational, diff, expand, symbols, total_degree

x, y, z = symbols('x y z')

PASS = []


def check(name, ok):
    PASS.append(bool(ok))
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}")


def singular(code, budget=1800):
    with tempfile.NamedTemporaryFile('w', suffix='.sing', delete=False) as f:
        f.write(code)
        path = f.name
    try:
        p = subprocess.run(['Singular', '-q', path], capture_output=True,
                           text=True, timeout=budget)
        if p.returncode in (-9, 137, 14) or 'no more memory' in p.stderr:
            raise RuntimeError('Singular ran out of memory')
        return p.stdout
    finally:
        os.unlink(path)


MAP = """
poly P = (1+x*y)^3*z + y^2*(1+x*y)*(4+3*x*y);
poly Q = y + 3*x*(1+x*y)^2*z + 3*x*y^2*(4+3*x*y);
poly R = 2*x - 3*x^2*y - x^3*z;
"""

print(__doc__)
print("=" * 72)
print("RESULT 0  the test object is what it claims to be")
print("=" * 72)
P = (1 + x*y)**3*z + y**2*(1 + x*y)*(4 + 3*x*y)
Q = y + 3*x*(1 + x*y)**2*z + 3*x*y**2*(4 + 3*x*y)
R = 2*x - 3*x**2*y - x**3*z
F = [P, Q, R]
J = Matrix([[diff(f, v) for v in (x, y, z)] for f in F])
print(f"   degrees (P,Q,R) = {[int(total_degree(expand(f))) for f in F]}")
print(f"   det JF = {expand(J.det())}")
check("det JF is the nonzero constant -2 (Alpoge's map is Keller)",
      expand(J.det()) == -2)
PTS = [(0, 0, Rational(-1, 4)),
       (1, Rational(-3, 2), Rational(13, 2)),
       (-1, Rational(3, 2), Rational(13, 2))]
imgs = [tuple(expand(f.subs({x: p[0], y: p[1], z: p[2]})) for f in F)
        for p in PTS]
for p, im in zip(PTS, imgs):
    print(f"   F{p} = {im}")
check("three DISTINCT points share one image, so F is not injective",
      len(set(PTS)) == 3 and imgs[0] == imgs[1] == imgs[2])

# =====================================================================
print()
print("=" * 72)
print("RESULT 1  the geometric degree")
print("=" * 72)
out = singular("ring S=(0,a,b,c),(x,y,z),dp;" + MAP + """
ideal G = std(ideal(P-a,Q-b,R-c));
"VDIM ", vdim(G);
int i; for (i=1;i<=size(G);i++){ if (pardeg(leadcoef(G[i]))>0){ "LC ", leadcoef(G[i]); } }
quit;""")
d = int(re.search(r"VDIM\s+(\d+)", out).group(1))
lcs = re.findall(r"LC\s+\((.+?)\)\s*$", out, re.M)
print(f"   vdim over Q(a,b,c) = {d}")
print(f"   {len(lcs)} non-constant leading coefficients")
check("the geometric degree is 3, matching the 3-point collision", d == 3)

# =====================================================================
print()
print("=" * 72)
print("RESULT 2  the non-properness set: exhaustive census of components")
print("=" * 72)
CANDS = {
    "C1  9abc-4b^2+18a": [(3, 3, "-2/9"), (-3, -4, "59/54"), (-2, -2, "13/9"),
                          (-5, -7, "286/315"), (-1, 3, "-2"), (7, 8, "65/252")],
    "C2  9ac-b": [(-7, 6, "-2/21"), (-3, 4, "-4/27"), (9, -3, "-1/27"),
                  (2, 3, "1/6"), (-3, -5, "5/27"), (5, -4, "-4/45")],
    "C3  b^3c+27a^2c^2-18abc-b^2+16a":
        [(5, -8, "-4/25"), (2, -5, "-7/27"), (-7, 4, "-16/27"),
         (0, -9, "-1/9"), (-5, 2, "-14/27"), (-4, -4, "-5/27")],
    "C4  3b^2c^2+36ac^2-20bc+16":
        [(1, 6, "1/6"), (-3, 2, "-2/3"), (-9, -6, "-1/9"),
         (-3, -6, "-2/15"), (4, 8, "1/7")],
    "C5  l4 irreducible factor":
        [(-9, 9, "-1/9"), (1, -8, "-16/5"), (-3, 0, "0"), (-4, -6, "1/6")],
}
calls = []
for pts in CANDS.values():
    calls += [f'"CNT ", cnt({a},{b},{c});' for (a, b, c) in pts]
out = singular("ring W=0,(x,y,z),dp;" + MAP + """
proc cnt(number A,number B,number C)
{ ideal G=std(ideal(P-A,Q-B,R-C));
  if (G[1]==1){return(0);} return(vdim(G)); }
""" + "\n".join(calls) + "\nquit;")
counts = [int(v) for v in re.findall(r"CNT\s+(\d+)", out)]
assert len(counts) == sum(len(p) for p in CANDS.values()), "count mismatch"
i, inSF = 0, {}
for nm, pts in CANDS.items():
    got = counts[i:i + len(pts)]
    i += len(pts)
    drops = all(g < d for g in got)
    inSF[nm] = drops
    print(f"   {nm:34s} fibres {got}  ->  "
          f"{'IN S_F, nu = ' + str(d - got[0]) if drops else 'not in S_F'}")
check("exactly one of the five candidate surfaces lies in S_F",
      sum(inSF.values()) == 1)
check("that component is C3, with nu = 2",
      inSF["C3  b^3c+27a^2c^2-18abc-b^2+16a"] and counts[12] == 1)
r = sum(inSF.values())
nus = [d - 1]
print(f"   => r = {r},  nu = {nus},  d = {d}")

# =====================================================================
print()
print("=" * 72)
print("RESULT 3  the verdict on T5-T8")
print("=" * 72)
budget = sum(n - 1 for n in nus)
print(f"   T6 claims  sum(nu_i - 1) >= d - 1 :  {budget} >= {d - 1} ?")
check("T6 is REFUTED (the transitivity budget fails on a real etale "
      "non-injective map)", not (budget >= d - 1))
print(f"   T8 claims  r >= 2 :  r = {r}")
check("T8 is REFUTED (the non-properness set is irreducible here)", r < 2)
print()
print("   WHY: pi_1 of the complement of an irreducible hypersurface is")
print("   generated by the meridian AND ITS CONJUGATES.  Conjugate")
print("   transpositions (12),(13) generate S_3 and act transitively on 3")
print("   sheets, so one component with nu = 2 suffices.  T6 counted one")
print("   generator per component; that is the error.")
check("T5 and T7 are NOT tested here and remain unverified [DERIVED]", True)

print()
print("=" * 72)
print(f"{sum(PASS)}/{len(PASS)} certifications passed.")
print("=" * 72)
print("""
GATE VERDICT: T6 and T8 REFUTED; T5 and T7 UNVERIFIED.

  Nothing may be built on T5-T8 as a family.  WP-2's congruence
  d = chi(C_L) mod 3 rests on T7, whose stablemates are now false and
  which was itself never verified - so WP-2 must not be run on this
  basis, and WP-5's "new handle" and WP-6 lose their support too.

  Per the handoff's decision tree this sends the session to WP-3, the
  GGHV (8,28) elimination, which depends on none of T5-T8.

  This is the gate doing exactly the job it was put there to do: the
  previous campaign's most expensive error was four sessions built on an
  unverified formula.  This one cost half a day.
""")
assert all(PASS), "a certification failed"
