"""night6 -- deterministic certificate for a UNIT-IDEAL verdict.

A Groebner engine's word is not evidence.  `modStd` (modstd.lib) computes over
Q by modular methods; its final test verifies that the input generators lie in
the ideal generated by the returned basis and that the basis is a standard
basis -- both of which the ideal <1> satisfies vacuously.  So a `modStd`
answer of "unit ideal" is a claim, not a proof.

This module turns such a claim into a certificate that can be checked without
trusting any Groebner engine at all:

    Singular is asked for cofactors c_1..c_m with   sum_i c_i * g_i = 1
    (`lift`), and the identity is then expanded and checked HERE, in exact
    rational arithmetic, from the generators g_i as this session built them.

If the check passes, 1 is in the ideal over Q and the ideal is the unit ideal,
independently of how the c_i were found.  A non-unit verdict needs no such
certificate: it is certified the other way round, by exhibiting a point of the
variety and substituting it exactly.
"""
import os, re, sys, time, subprocess
from fractions import Fraction as F

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import char0_implicit as CIM

SCRATCH = os.environ.get('N6SCRATCH', '/tmp')


def parse_sing_poly(s, varset):
    """Singular polynomial string -> dict monomial -> Fraction.

    monomial = tuple of (varname, exponent) sorted, as in char0_implicit.
    """
    s = s.replace(' ', '').replace('\n', '')
    out = {}
    for sign, body in re.findall(r'([+-]?)([^+-]+)', s):
        if not body:
            continue
        coef = F(1)
        mon = {}
        for part in body.split('*'):
            if not part:
                continue
            m = re.fullmatch(r'(\d+)(?:/(\d+))?', part)
            if m:
                coef *= F(int(m.group(1)), int(m.group(2) or 1))
                continue
            m = re.fullmatch(r'([A-Za-z]\w*)(?:\^(\d+))?', part)
            assert m, ("unparsed factor", part, s[:200])
            v = m.group(1)
            assert v in varset, ("unknown variable", v)
            mon[v] = mon.get(v, 0) + int(m.group(2) or 1)
        if sign == '-':
            coef = -coef
        k = tuple(sorted(mon.items()))
        out[k] = out.get(k, F(0)) + coef
    return {m: c for m, c in out.items() if c}


def certify_unit(eqs, varnames, tag, timeout=86400, order='dp', char=0,
                 engine='modStd'):
    """Ask Singular for a representation of 1, then verify it here.

    Returns (ok, n_cofactors, seconds, path, detail).
    """
    src = []
    if engine == 'modStd':
        src.append('LIB "modstd.lib";')
    src.append("ring R = %d,(%s),%s;" % (char, ",".join(varnames), order))
    en = []
    for i, e in enumerate(eqs):
        src += CIM.stmts(CIM.sing_terms(e), "q%d" % i)
        en.append("q%d" % i)
    src += ["ideal I = %s;" % ",".join(en),
            "option(redSB);",
            "ideal G = %s;" % ("modStd(I, 1)" if engine == 'modStd'
                               else "std(I)"),
            '"ISUNIT:"; int uu = (size(G)==1 && G[1]==1); uu;',
            "if (uu == 1) {",
            "  matrix M = lift(I, ideal(1));",
            '  "COFACTORS:"; nrows(M);',
            "  int i;",
            "  for (i = 1; i <= nrows(M); i++) { M[i,1]; }",
            "}",
            '"END";', "quit;"]
    path = os.path.join(SCRATCH, 'cert_%s.sing' % tag)
    open(path, 'w').write("\n".join(src) + "\n")
    t0 = time.time()
    out = subprocess.run(['Singular', '-q', path], capture_output=True,
                         text=True, timeout=timeout)
    txt = out.stdout
    open(os.path.join(SCRATCH, 'cert_%s.out' % tag), 'w').write(txt)
    secs = time.time() - t0
    lines = [l.rstrip() for l in txt.splitlines()
             if l.strip() and not l.startswith('// **')]
    assert 'ISUNIT:' in [l.strip() for l in lines], txt[:3000]
    st = [l.strip() for l in lines]
    isunit = int(st[st.index('ISUNIT:') + 1]) == 1
    if not isunit:
        return False, 0, secs, path, "not the unit ideal -- no certificate"
    n = int(st[st.index('COFACTORS:') + 1])
    body = lines[st.index('COFACTORS:') + 2:st.index('END')]
    # Singular prints one polynomial per line
    assert len(body) == n, ("expected %d cofactor lines, got %d"
                            % (n, len(body)))
    varset = set(varnames)
    acc = {}
    for c_s, g in zip(body, eqs):
        c = parse_sing_poly(c_s, varset)
        acc = CIM.mp_add(acc, CIM.mp_mul(c, g))
    ok = (acc == {(): F(1)})
    return ok, n, secs, path, ("sum c_i*g_i == 1 : %s ; residual terms: %d"
                               % (ok, len(CIM.mp_add(acc, {(): F(-1)}))))


if __name__ == '__main__':
    import argparse, json
    ap = argparse.ArgumentParser()
    ap.add_argument('what')
    ap.add_argument('--timeout', type=int, default=86400)
    ap.add_argument('--char', type=int, default=0)
    ap.add_argument('--engine', default='modStd')
    a = ap.parse_args()
    W = a.what
    if W in ('C2', 'C3'):
        eqs, vn, meta = CIM.build('B', W == 'C3', zero_ps=True)
    else:
        eqs, vn, meta = CIM.build(W[0], W.endswith('rab'))
    print("certify %s : %d generators, %d variables"
          % (W, len(eqs), len(vn)), flush=True)
    ok, n, secs, path, detail = certify_unit(
        eqs, vn, W if a.char == 0 else "%s_p%d" % (W, a.char),
        timeout=a.timeout, char=a.char,
        engine=a.engine if a.char == 0 else 'std')
    print("CERT %s : verified = %s, %d cofactors, %.1fs  [%s]"
          % (W, ok, n, secs, detail), flush=True)
