"""Session 43 -- the general C*-equivariant map in dimension 3, and the plane
PDE its Keller condition becomes.

WHERE THIS COMES FROM.  descent_theorem.py censused all seven known
counterexamples and found more than the perfect square it was looking for:
the cofactor  alpha = F_p / x  is AFFINE-LINEAR in the invariants (u,v) in
every single case,

    alpoge d3      alpha = -3u - v + 2
    gao G d4       alpha = -4u - v + 2
    gallagher d3   alpha = -(3u - 2v - 2)/2
    gallagher d6   alpha = -(19u - 14v - 14)/14
    constructed d6 alpha = -3u - v + 2
    constructed d7 alpha = -9u - v + 2
    gallagher d12  alpha = -(87u - 65v - 65)/65

alpha linear means F_p = x*(a u + b v + c) = a x^2 y + b x^3 z + c x, which is
exactly the "monomial twist" shape that pathS_highdegree.py found blocking
Path S: the z-coefficient of the z-linear component is the pure monomial b x^3,
so the slice's centre B(0,y) is constant and every slice is C* x C, never C^2.

So the two independent obstructions are ONE obstruction, and it has one
escape: a counterexample with  deg alpha >= 2.  This file asks whether the
Keller condition permits one.

THE SETUP.  For source and target weights (-1,1,2) with invariants u = xy,
v = x^2 z, the weight-w pieces of C[x,y,z] are free C[u,v]-modules on

    weight -1 :  x                     (so F_p = x*alpha)
    weight +1 :  y, xz                 (so F_q = y*beta + xz*epsilon)
    weight +2 :  y^2, z                (so F_r = y^2*delta + z*gamma)

-- proved below by exhibiting the generators and checking every monomial of
weight w up to a large degree is a C[u,v]-combination of them.  det JF then
has weight 0, so it is itself a polynomial Psi(u,v), and

    F is Keller   <=>   Psi(u, v) is a nonzero constant

is a PDE in the plane for five unknown functions of two variables.  That PDE
is derived here symbolically and checked against all seven maps.
"""
import os
import sys
import sympy as sp

x, y, z = sp.symbols('x y z')
u, v = sp.symbols('u v')

HERE = os.path.dirname(os.path.abspath(__file__))
MAPS = os.path.join(HERE, 'maps')
OUT = []


def rec(name, ok, detail=''):
    OUT.append((name, bool(ok)))
    print(("  PASS  " if ok else "  FAIL  ") + name + (("   " + detail) if detail else ""))
    return bool(ok)


def load(path):
    src = open(path).read()
    g = {'sp': sp, 'x': x, 'y': y, 'z': z, 'w': sp.Symbol('w'),
         'R': sp.Rational, 'sys': sys, 'FAILURES': []}
    end = src.index('\n', src.index('F3 = (') + src[src.index('F3 = ('):].index('\n)'))
    exec(compile(src[:end + 2], '<m>', 'exec'), g)
    return [sp.expand(g['F1']), sp.expand(g['F2']), sp.expand(g['F3'])]


def wt(i, j, l):
    return -i + j + 2 * l


# ------------------------------------------------- [A] the module generators
GENS = {-1: [(1, 0, 0)],
        1: [(0, 1, 0), (1, 0, 1)],
        2: [(0, 2, 0), (0, 0, 1)]}
NAMES = {-1: ['x'], 1: ['y', 'x z'], 2: ['y^2', 'z']}


def part_A(bound=14):
    print("[A]  the weight-w pieces are free C[u,v]-modules on the listed generators")
    for w in (-1, 1, 2):
        bad = []
        for i in range(bound):
            for j in range(bound):
                for l in range(bound):
                    if wt(i, j, l) != w:
                        continue
                    # is x^i y^j z^l = gen * u^a v^b for some generator and a,b >= 0 ?
                    hit = False
                    for (gi, gj, gl) in GENS[w]:
                        # gen * u^a v^b = x^(gi+a+2b) y^(gj+a) z^(gl+b)
                        a = j - gj
                        b = l - gl
                        if a >= 0 and b >= 0 and gi + a + 2 * b == i:
                            hit = True
                            break
                    if not hit:
                        bad.append((i, j, l))
        rec("weight %+d generated by {%s} (all monomials up to degree %d)"
            % (w, ', '.join(NAMES[w]), bound), not bad,
            ("missed %s" % bad[:4]) if bad else "")
    print()


# --------------------------------------------- [B] read alpha..epsilon off
def to_uv(poly, xpow):
    """poly must equal x^xpow * P(xy, x^2 z).  Return P, or None."""
    P = sp.Poly(poly, x, y, z)
    out = 0
    for (i, j, l), c in P.terms():
        if i != j + 2 * l + xpow:
            return None
        out += c * u**j * v**l
    return sp.expand(out)


def perm_sign(p):
    """Sign of the permutation p (a tuple of 0,1,2)."""
    s = 1
    for i in range(len(p)):
        for j in range(i + 1, len(p)):
            if p[i] > p[j]:
                s = -s
    return s


def decompose(F):
    """Return ((alpha,beta,gamma,delta,epsilon), (p,q,r)) or None.

    (p,q,r) are the positions in the FILE's component order of the weight
    -1, +1, +2 components.  Psi below is derived for the canonical order
    (p,q,r) = (0,1,2); Gallagher lists his components in the order (2,1,0),
    an ODD permutation, so his det JF is the negative of Psi.  An earlier
    version of this file compared Psi to det JF without that sign and
    reported his three maps as failures.  The sign is now carried explicitly.
    """
    ws = []
    for f in F:
        t = sp.Poly(f, x, y, z).terms()
        s = {wt(*m) for m, _c in t}
        ws.append(s.pop() if len(s) == 1 else None)
    if None in ws or sorted(ws) != [-1, 1, 2]:
        return None
    p, q, r = ws.index(-1), ws.index(1), ws.index(2)
    alpha = to_uv(F[p], 1)
    # weight +1 = y*beta + xz*epsilon : split monomials by whether l>0 forces xz
    Pq = sp.Poly(F[q], x, y, z)
    beta = epsilon = 0
    for (i, j, l), c in Pq.terms():
        if j >= 1:                       # y * u^(j-1) v^l  needs i = j-1+2l
            if i == j - 1 + 2 * l:
                beta += c * u**(j - 1) * v**l
                continue
        # else xz * u^a v^b = x^(1+a+2b) y^a z^(1+b)
        a, b = j, l - 1
        if b >= 0 and i == 1 + a + 2 * b:
            epsilon += c * u**a * v**b
        else:
            return None
    Pr = sp.Poly(F[r], x, y, z)
    delta = gamma = 0
    for (i, j, l), c in Pr.terms():
        if l >= 1:                       # z * u^j v^(l-1) needs i = j + 2(l-1)
            if i == j + 2 * (l - 1):
                gamma += c * u**j * v**(l - 1)
                continue
        a, b = j - 2, l
        if a >= 0 and i == a + 2 * b:
            delta += c * u**a * v**b
        else:
            return None
    return [sp.expand(e) for e in (alpha, beta, gamma, delta, epsilon)], (p, q, r)


def part_B():
    print("[B]  alpha, beta, gamma, delta, epsilon for every known counterexample")
    files = [('alpoge_dim3_degree3.py', 'alpoge d3'),
             ('gao_G_dim3_degree4.py', 'gao G d4'),
             ('gallagher_dim3_degree3.py', 'gallagher d3'),
             ('gallagher_dim3_degree6.py', 'gallagher d6'),
             ('dim3_degree6.py', 'constructed d6'),
             ('dim3_degree7.py', 'constructed d7'),
             ('gallagher_dim3_degree12.py', 'gallagher d12')]
    data = []
    for fn, label in files:
        path = os.path.join(MAPS, fn)
        if not os.path.exists(path):
            continue
        F = load(path)
        dd = decompose(F)
        if dd is None:
            rec("%s: decomposes into (alpha,beta,gamma,delta,epsilon)" % label, False)
            continue
        d, perm = dd
        # reconstruct and compare -- the real check
        p_ = [w for w in [0, 1, 2]]
        al, be, ga, de, ep = d
        sub = {u: x * y, v: x**2 * z}
        rebuilt = sorted([sp.expand(x * al.subs(sub)),
                          sp.expand(y * be.subs(sub) + x * z * ep.subs(sub)),
                          sp.expand(y**2 * de.subs(sub) + z * ga.subs(sub))],
                         key=lambda e: sp.Poly(e, x, y, z).total_degree())
        orig = sorted(F, key=lambda e: sp.Poly(e, x, y, z).total_degree())
        ok = all(sp.expand(a - b) == 0 for a, b in zip(rebuilt, orig))
        degs = tuple(sp.Poly(e, u, v).total_degree() if e != 0 else -1 for e in d)
        rec("%s: F rebuilt exactly from (alpha,beta,gamma,delta,epsilon)" % label, ok,
            "degrees (a,b,g,d,e) = %s, component order %s, sign %+d"
            % (degs, perm, perm_sign(perm)))
        print("           alpha   = %s" % sp.factor(al))
        print("           beta    = %s" % (sp.factor(be) if sp.Poly(be, u, v).total_degree() <= 3 else '[deg %d]' % sp.Poly(be, u, v).total_degree()))
        print("           epsilon = %s" % (sp.factor(ep) if ep == 0 or sp.Poly(ep, u, v).total_degree() <= 3 else '[deg %d]' % sp.Poly(ep, u, v).total_degree()))
        data.append((label, d, perm))
    print()
    lin = [lb for lb, d, _p in data if d[0] != 0 and sp.Poly(d[0], u, v).total_degree() == 1]
    rec("alpha is AFFINE-LINEAR in every known counterexample",
        len(lin) == len(data), "%d/%d" % (len(lin), len(data)))
    # I guessed epsilon would vanish (the xz generator looked decorative).
    # It does not: it is nonzero in all seven, and its degree grows with the
    # map.  Recording the measurement, not the guess.
    epsnz = [lb for lb, d, _p in data if d[4] != 0]
    rec("epsilon is NONZERO in every known counterexample: the xz generator "
        "of the weight-+1 module is always used",
        len(epsnz) == len(data), "%d/%d" % (len(epsnz), len(data)))
    degs_a = {sp.Poly(d[0], u, v).total_degree() for _lb, d, _p in data}
    degs_rest = {sp.Poly(e, u, v).total_degree() for _lb, d, _p in data
                 for e in d[1:] if e != 0}
    rec("alpha alone stays at degree 1 while the others grow without bound",
        degs_a == {1} and max(degs_rest) > 10,
        "deg alpha in %s, deg of the rest up to %d" % (sorted(degs_a), max(degs_rest)))
    print()
    return data


# --------------------------------------- [C] the Keller condition as a plane PDE
def part_C(data):
    print("[C]  det JF as a polynomial Psi(u,v) in alpha..epsilon and their partials")
    al = sp.Function('a')(u, v)
    be = sp.Function('b')(u, v)
    ga = sp.Function('g')(u, v)
    de = sp.Function('d')(u, v)
    ep = sp.Function('e')(u, v)
    sub = {u: x * y, v: x**2 * z}

    def S(f):
        return f.subs(sub, simultaneous=True)

    F = [x * S(al),
         y * S(be) + x * z * S(ep),
         y**2 * S(de) + z * S(ga)]
    J = sp.Matrix([[sp.diff(f, w_) for w_ in (x, y, z)] for f in F])
    det = sp.expand(J.det().doit())
    # det JF has weight 0, hence equals Psi(xy, x^2 z).  Set x = 1: u=y, v=z.
    det1 = sp.simplify(det.subs(x, 1))
    Psi = det1.subs({y: u, z: v}, simultaneous=True)
    Psi = sp.simplify(sp.expand(Psi.doit()))
    print("     Psi(u,v) =")
    print("       " + sp.sstr(sp.collect(sp.expand(Psi), [al, be, ga, de, ep])))
    # verify weight-0: the substitution really was consistent
    back = sp.expand(Psi.subs({u: x * y, v: x**2 * z}, simultaneous=True) - det)
    rec("det JF really is weight 0: Psi(xy, x^2 z) = det JF identically",
        sp.simplify(back) == 0, "residual %s" % sp.simplify(back))

    # ---- verify against every known map
    nok = 0
    for label, d, perm in data:
        rep = {al: d[0], be: d[1], ga: d[2], de: d[3], ep: d[4]}
        P = Psi
        for k_, val in rep.items():
            P = P.subs(sp.Derivative(k_, u), sp.diff(val, u))
            P = P.subs(sp.Derivative(k_, v), sp.diff(val, v))
        P = P.subs(rep)
        P = sp.expand(sp.simplify(P))
        # compare with the true det JF
        F0 = load(os.path.join(MAPS, dict(FILES)[label]))
        J0 = sp.Matrix([[sp.diff(f, w_) for w_ in (x, y, z)] for f in F0])
        true = sp.expand(J0.det())
        sgn = perm_sign(perm)
        ok = sp.simplify(P - sgn * true) == 0
        nok += ok
        rec("%s: Psi = %s * det JF  (component order %s, det JF = %s)"
            % (label, '+1' if sgn > 0 else '-1', perm, true), ok,
            "" if ok else "got %s" % P)
    print()
    return Psi, (al, be, ga, de, ep)


FILES = [('alpoge d3', 'alpoge_dim3_degree3.py'),
         ('gao G d4', 'gao_G_dim3_degree4.py'),
         ('gallagher d3', 'gallagher_dim3_degree3.py'),
         ('gallagher d6', 'gallagher_dim3_degree6.py'),
         ('constructed d6', 'dim3_degree6.py'),
         ('constructed d7', 'dim3_degree7.py'),
         ('gallagher d12', 'gallagher_dim3_degree12.py')]


if __name__ == '__main__':
    part_A()
    data = part_B()
    part_C(data)
    nf = sum(1 for _n, ok in OUT if not ok)
    print("=" * 72)
    print("%d checks, %d FAILED" % (len(OUT), nf))
    sys.exit(1 if nf else 0)
