"""night15 -- EXACT-G1: the period screen in closed form for the whole
v-power family  P = h0*v + c*(x-a)^n * v^m,  v = y + t(x)/2,  m >= 2.

REDUCTION.  y -> y - t(x)/2 and x -> x + a are triangular automorphisms of
Jacobian 1, so (G3) they carry fibres to fibres by maps pulling eta back to eta
and the period verdict is unchanged.  After them

        P = h0*y + c*x^n*y^m.

FORM.  On the fibre {P = lam},  c x^n y^m = lam - h0 y,  and
        P_x = c*n*x^(n-1)*y^m,
so
        eta = dy/P_x = x*dy/(c*n*x^n*y^m) = x*dy / ( n*(lam - h0*y) ).      (*)

SUPERELLIPTIC MODEL.  Put z = c*y^m*x.  Raising  c y^m x^n = lam - h0 y  to a
suitable power gives

        z^n = c^(n-1) * y^(m(n-1)) * (lam - h0*y)  =:  R(y),
        eta = z*dy / ( c*n*y^m*(lam - h0*y) ).                              (**)

so the fibre is the superelliptic curve z^n = R(y), an n-sheeted cover of the
y-line, and eta is explicit on it.

PLACES (lam != 0, so lam/h0 != 0).
  y = 0        : R vanishes to order m(n-1); gcd(n, m(n-1)) = gcd(n, m) =: d0
                 places, each with ramification n/d0.  There x -> infinity, so
                 these are PUNCTURES.
  y = lam/h0   : R has a simple zero; one place, ramification n.  There x = 0,
                 an honest AFFINE point of the fibre.
  y = infinity : deg R = m(n-1)+1 = 1-m (mod n); gcd(n, m-1) =: dinf places.
                 There x -> 0 (m >= 2), so these are PUNCTURES.

GENUS (Riemann-Hurwitz for the degree-n cover of the y-line; the three loci
above are the only ramification):
    2 - 2g = 2n - (n - d0) - (n - 1) - (n - dinf)
    ==>  2g = n + 1 - gcd(n, m) - gcd(n, m-1).
(For m = 2 this is n - gcd(n,2), i.e. g = floor((n-1)/2), matching EXACT-HE.)

LEADING EXPONENTS OF eta.
  at y = infinity: R ~ -c^(n-1) h0 y^(m(n-1)+1), so z ~ const*y^((m(n-1)+1)/n)
      and by (**) eta ~ const * y^((1-m-n)/n) dy.  With y = tau^(-n/dinf) this
      is  const * tau^((m-1)/dinf - 1) d tau:  NO residue for m >= 2, and
      holomorphic there.
  at y = 0: R ~ c^(n-1) lam y^(m(n-1)), z ~ const*y^(m(n-1)/n), so by (**)
      eta ~ const * y^(-m/n) dy.  With y = tau^(n/d0) this is
      const * tau^((n-m)/d0 - 1) d tau:  a RESIDUE exactly when n = m, a pole
      (of order (m-n)/d0 + 1, residue 0) when n < m, holomorphic when n > m.

VERDICTS (lam != 0).
  (i)   n = m           : nonzero residues at the n places over y = 0.
                          With u = z/y^(n-1) (so u^n = c^(n-1)(lam - h0 y)),
                          eta = u dy/(c n y (lam - h0 y)) and
                              Res = u0 / (c*n*lam),   u0^n = c^(n-1)*lam,
                          one for each n-th root u0.  They sum to 0 (the sum of
                          all n-th roots of a number vanishes for n >= 2), which
                          is control C3 discharged symbolically.
                          VERDICT: NONVANISHING.
  (ii)  n != m and g = 0: no residues (by the exponents above) and the compact
                          model is P^1, whose H^1 vanishes; H_1 of the fibre is
                          generated by the loops around the punctures, whose
                          periods are 2 pi i times the residues.
                          VERDICT: VANISHING.
  (iii) n > m and g >= 1: eta is holomorphic at every place, hence a nonzero
                          holomorphic 1-form on a compact curve of genus >= 1.
                          VERDICT: NONVANISHING.
  (iv)  n < m and g >= 1: eta is of the second kind (poles, zero residues) and
                          the class in H^1 of the compact model is not settled
                          by these exponents.
                          VERDICT: DEFERRED_TO_NUM.
"""

from math import gcd


def screen(n, m, lam_is_zero=False):
    if m < 2 or n < 1:
        return {"applicable": False, "reason": "needs m >= 2, n >= 1"}
    if lam_is_zero:
        return {"applicable": False, "reason": "derivation assumes lam != 0"}
    d0, dinf = gcd(n, m), gcd(n, m - 1)
    two_g = n + 1 - d0 - dinf
    assert two_g >= 0 and two_g % 2 == 0, (n, m, two_g)
    g = two_g // 2
    out = {"applicable": True, "n": n, "m": m, "genus": g,
           "n_places_at_infinity": d0 + dinf,
           "places_over_y0": d0, "places_over_yinf": dinf,
           "eta_exponent_at_y0_minus_1": "(n-m)/d0",
           "sum_residues": "0"}
    if n == m:
        out.update({"verdict": "NONVANISHING", "case": "i",
                    "witness": "residue u0/(c*n*lam) at each of the n places "
                               "over y = 0, u0^n = c^(n-1)*lam",
                    "residues_nonzero": True})
    elif g == 0:
        out.update({"verdict": "VANISHING", "case": "ii",
                    "witness": "all residues zero and the compact model is P^1",
                    "residues_nonzero": False})
    elif n > m:
        out.update({"verdict": "NONVANISHING", "case": "iii",
                    "witness": "nonzero holomorphic 1-form on a compact curve "
                               "of genus %d" % g,
                    "residues_nonzero": False})
    else:
        out.update({"verdict": "DEFERRED_TO_NUM", "case": "iv",
                    "witness": "second-kind differential, genus %d" % g,
                    "residues_nonzero": False})
    return out


if __name__ == "__main__":
    print("  n   m  genus  places  verdict")
    for m in range(2, 8):
        for n in range(1, 13):
            r = screen(n, m)
            print("%3d %3d %5d %6d  %s" % (n, m, r["genus"],
                                           r["n_places_at_infinity"], r["verdict"]))
