"""night15 -- NUM-MONO: the general (any deg_y) numerical period instrument.

WHAT IS MEASURED
----------------
For P in Q[x,y] and a value c, the fibre F_c = {P = c} carries the
Gelfand-Leray form

    eta = dy/P_x = -dx/P_y            (dP ^ eta = dx ^ dy)

If P has a Keller mate Q (P_x Q_y - P_y Q_x = 1) then eta = dQ|_{F_c} is
EXACT on F_c, so every period of eta over a closed cycle of F_c vanishes.
This module measures those periods.

METHOD
------
Write f(x,y) = P(x,y) - c as a polynomial in y of degree dy over Q[x].
Project F_c -> C_x.  Off the branch set

    B = { roots of disc_y f } u { roots of lc_y f }

the projection is a dy-sheeted covering.  pi_1(C \ B, x_0) is generated by
the loops gamma_j = (radial segment x_0 -> near b_j) . (circle about b_j) .
(segment back).  Lifting gamma_j from the sheet k gives
    - a permutation sigma_j(k) (the sheet reached), and
    - a number v_{j,k} = integral of eta along that lifted path.
A closed cycle of F_c is exactly a lift that returns to its starting sheet,
so ALL periods vanish  <=>  there is a "potential" u : sheets -> C with

    v_{j,k} = u(sigma_j(k)) - u(k)      for all j, k.

Solving that potential problem by union-find over the graph on the sheets
(nodes) with edges k -> sigma_j(k) of weight v_{j,k} does two things at once:
every edge that closes a loop yields an explicit period (the discrepancy),
and consistency of the whole system certifies that no period is missed.
Loops around ramification points are contractible IN F_c (those points are
honest points of the smooth fibre), so nothing is over-counted.

The same continuation along a large circle |x| = R (enclosing B) gives the
monodromy at infinity: its cycles are the places of F_c over x = infinity,
and the lifted integrals over the cycles are 2*pi*i times the residues there.
The residues over ALL places must sum to zero -- that is control C3.

ACCURACY
--------
Everything is done twice, at step budget N and 2N; the reported error
estimate for each quantity is the modulus of the difference.  A period is
called VANISHING only when its modulus is below tol * scale, where
scale = max(1, largest |v| seen on the lifts), and the error estimate is
itself below that threshold.
"""

import cmath
import math
import numpy as np

# ------------------------------------------------------------------ helpers


def to_ycoeffs(P):
    """[a_0(x), ..., a_dy(x)] as numpy coefficient arrays (ascending in x)."""
    dy = max(j for (i, j) in P) if P else 0
    dx_ = max(i for (i, j) in P) if P else 0
    A = np.zeros((dy + 1, dx_ + 1), dtype=np.complex128)
    for (i, j), v in P.items():
        A[j, i] += complex(v)
    return A


def _polyval_x(A, x):
    """evaluate every row of A (ascending x-coeffs) at x -> vector over j."""
    # Horner in x, descending
    out = np.zeros(A.shape[0], dtype=np.complex128)
    for i in range(A.shape[1] - 1, -1, -1):
        out = out * x + A[:, i]
    return out


def ycoef_desc(A, x):
    """y-coefficients at this x, DESCENDING order (for np.roots)."""
    v = _polyval_x(A, x)
    return v[::-1]


def _roots_at(A, x, tol_lead=1e-13):
    c = ycoef_desc(A, x)
    # strip leading (near-)zeros
    k = 0
    scale = max(abs(c).max(), 1e-300)
    while k < len(c) - 1 and abs(c[k]) < tol_lead * scale:
        k += 1
    return np.roots(c[k:]) if len(c) - k > 1 else np.array([], dtype=np.complex128)


def make_evals(P):
    A = to_ycoeffs(P)
    Ax = to_ycoeffs({(i - 1, j): v * i for (i, j), v in P.items() if i > 0})
    Ay = to_ycoeffs({(i, j - 1): v * j for (i, j), v in P.items() if j > 0})

    def f(x, y, c):
        v = _polyval_x(A, x)
        return np.polyval(v[::-1], y) - c

    def fx(x, y):
        if Ax.size == 0:
            return 0.0 + 0j
        v = _polyval_x(Ax, x)
        return np.polyval(v[::-1], y)

    def fy(x, y):
        if Ay.size == 0:
            return 0.0 + 0j
        v = _polyval_x(Ay, x)
        return np.polyval(v[::-1], y)

    return A, f, fx, fy


# ------------------------------------------------------------- branch points


def _disc_and_lc_roots(P, c):
    """branch set of the projection F_c -> C_x, as complex numbers."""
    import sympy as sp
    x, y = sp.symbols("x y")
    expr = 0
    for (i, j), v in P.items():
        expr += sp.Rational(v.numerator, v.denominator) * x ** i * y ** j
    expr = sp.expand(expr - sp.nsimplify(c))
    pol = sp.Poly(expr, y)
    if pol.degree() < 1:
        raise ValueError("deg_y < 1")
    lc = sp.Poly(pol.LC(), x) if pol.LC().free_symbols else None
    D = sp.Poly(sp.discriminant(pol, y), x)
    out = []
    for pp in [D] + ([lc] if lc is not None and sp.Poly(lc, x).degree() >= 1 else []):
        if pp.degree() < 1:
            continue
        # squarefree part first: a repeated factor of the discriminant is ONE
        # branch point, and numerical roots of a repeated factor would
        # otherwise split into a cluster of spurious ones.
        pp = sp.Poly(sp.prod([f for f, _ in sp.factor_list(pp.as_expr())[1]]), x)
        if pp.degree() < 1:
            continue
        co = [complex(v) for v in pp.all_coeffs()]
        out.extend(list(np.roots(co)))
    # dedupe
    uniq = []
    for b in out:
        if not any(abs(b - u) < 1e-9 * max(1.0, abs(b)) for u in uniq):
            uniq.append(complex(b))
    return uniq


# ------------------------------------------------ continuation + integration

GL8_X = np.array([-0.9602898564975363, -0.7966664774136267, -0.5255324099163290,
                  -0.1834346424956498, 0.1834346424956498, 0.5255324099163290,
                  0.7966664774136267, 0.9602898564975363])
GL8_W = np.array([0.1012285362903763, 0.2223810344533745, 0.3137066458778873,
                  0.3626837833783620, 0.3626837833783620, 0.3137066458778873,
                  0.2223810344533745, 0.1012285362903763])


class Tracker(object):
    def __init__(self, P, c):
        self.P = P
        self.c = complex(c)
        self.A, self.f, self.fx, self.fy = make_evals(P)
        self.Ac = self.A.copy()
        self.Ac[0, 0] -= self.c          # y-coeffs of P - c
        self.Ady = to_ycoeffs({(i, j - 1): v * j
                               for (i, j), v in P.items() if j > 0})
        self._cx, self._cv = None, None
        self.qtol = 1e-9      # per-panel quadrature tolerance (adaptive)

    def roots(self, x):
        return _roots_at(self.Ac, x)

    def _cf(self, x):
        """(f, f') y-coefficients at this x, descending -- cached per x."""
        if self._cx == x:
            return self._cv
        cf = _polyval_x(self.Ac, x)[::-1]
        cd = _polyval_x(self.Ady, x)[::-1] if self.Ady.size else np.array([0j])
        self._cx, self._cv = x, (cf, cd)
        return self._cv

    def _newton_vec(self, x, ys, iters=40):
        cf, cd = self._cf(x)
        y = np.array(ys, dtype=np.complex128)
        for _ in range(iters):
            fv = np.polyval(cf, y)
            d = np.polyval(cd, y)
            with np.errstate(divide="ignore", invalid="ignore"):
                step = np.where(d != 0, fv / np.where(d != 0, d, 1.0), 0.0)
            y = y - step
            if np.max(np.abs(step)) < 1e-15 * max(1.0, float(np.max(np.abs(y)))):
                break
        return y

    def _newton(self, x, y, iters=40):
        return complex(self._newton_vec(x, [y], iters)[0])

    def _substep(self, a, b, ys):
        """One Gauss-Legendre substep a -> b; returns (ys_at_b, contributions).

        The sheets are carried to the quadrature nodes by Newton from the
        running value, so the integrand is evaluated on the correct sheet.
        """
        mid, half = 0.5 * (a + b), 0.5 * (b - a)
        yn = np.array(ys, dtype=np.complex128)
        acc = np.zeros(len(ys), dtype=np.complex128)
        for q in range(len(GL8_X)):
            xq = mid + half * GL8_X[q]
            yn = self._newton_vec(xq, yn)
            _, cd = self._cf(xq)
            d = np.polyval(cd, yn)
            if np.any(d == 0):
                raise RuntimeError("P_y = 0 on a quadrature node")
            acc += GL8_W[q] * half * (-1.0 / d)
        return self._newton_vec(b, ys), acc

    def _validate(self, x, ys):
        """the tracked sheets must be a bijection onto the true root set."""
        tr = self.roots(x)
        if len(tr) != len(ys):
            return False
        used = set()
        sep = 1e18
        if len(tr) > 1:
            M = np.abs(tr[:, None] - tr[None, :]) + np.eye(len(tr)) * 1e18
            sep = M.min()
        for k in range(len(ys)):
            d = np.abs(tr - ys[k])
            o = int(np.argmin(d))
            if o in used or d[o] > 0.25 * sep + 1e-9 * max(1.0, abs(ys[k])):
                return False
            used.add(o)
        return True

    def transport(self, xs, ys, nsub, maxdepth=22):
        """Follow all sheets ys (roots at xs[0]) along the polyline xs.

        Adaptive: every substep is validated against the true root set at its
        endpoint; a failure halves the step.  Returns (ys_end, integrals) with
        integrals[k] = int of eta along the lift starting at sheet k, and
        eta = -dx/P_y.
        """
        ys = np.array(ys, dtype=np.complex128)
        acc = np.zeros(len(ys), dtype=np.complex128)
        for s in range(len(xs) - 1):
            stack = [(xs[s], xs[s + 1], 0)]
            # seed subdivision
            seg = []
            for t in range(nsub):
                seg.append((xs[s] + (xs[s + 1] - xs[s]) * (t / nsub),
                            xs[s] + (xs[s + 1] - xs[s]) * ((t + 1) / nsub), 0))
            stack = seg[::-1]
            while stack:
                a, b, dep = stack.pop()
                mid = 0.5 * (a + b)
                try:
                    # coarse: one Gauss-Legendre panel on [a, b]
                    ycoarse, acc_c = self._substep(a, b, ys)
                    # fine: two panels.  Their difference is the QUADRATURE
                    # error estimate -- validating the sheet identification
                    # alone is not enough, and an earlier version of this file
                    # returned converged-looking but wrong periods without it.
                    ymid, acc1 = self._substep(a, mid, ys)
                    yfine, acc2 = self._substep(mid, b, ymid)
                    ok = (self._validate(mid, ymid) and self._validate(b, yfine)
                          and self._validate(b, ycoarse))
                    if ok:
                        qerr = float(np.max(np.abs(acc_c - (acc1 + acc2))))
                        ok = qerr <= self.qtol
                    contrib = acc1 + acc2
                    ynew = yfine
                except (RuntimeError, OverflowError, FloatingPointError):
                    ok = False
                if ok:
                    ys, acc = ynew, acc + contrib
                else:
                    if dep >= maxdepth:
                        raise RuntimeError("substep refinement exhausted")
                    m = 0.5 * (a + b)
                    stack.append((m, b, dep + 1))
                    stack.append((a, m, dep + 1))
        return ys, acc

    def match(self, ys_end, ys_ref):
        """permutation: sheet k ends at ys_ref[perm[k]]."""
        perm = []
        used = set()
        for k in range(len(ys_end)):
            d = np.abs(ys_ref - ys_end[k])
            order = np.argsort(d)
            pick = None
            for o in order:
                if o not in used:
                    pick = int(o)
                    break
            if d[pick] > 1e-5 * max(1.0, abs(ys_end[k])):
                raise RuntimeError("sheet identification failed (gap %.2e)" % d[pick])
            perm.append(pick)
            used.add(pick)
        return perm


def _circle(cen, r, n):
    return [cen + r * cmath.exp(2j * math.pi * t / n) for t in range(n + 1)]


def screen_fibre(P, c, nsub=6, ncirc=64, seed=11, verbose=False):
    """The period screen on the single fibre {P = c}.  Returns a dict."""
    T = Tracker(P, c)
    B = _disc_and_lc_roots(P, c)
    rng = np.random.default_rng(seed)
    R = max([abs(b) for b in B] + [1.0]) * 2.5 + 1.0
    for attempt in range(8):
        x0 = R * cmath.exp(1j * (0.37 + 0.11 * attempt)) * (1 + 0.01 * attempt)
        ok = True
        for b in B:
            # distance from b to the segment 0..x0 direction is irrelevant; we
            # only need the radial segments below to miss the other points.
            pass
        if ok:
            break
    ys0 = T.roots(x0)
    dy = len(ys0)
    if dy == 0:
        return {"error": "no sheets"}

    edges = []      # (j, k, sigma_j(k), value)
    info_loops = []
    finite_cycles = 0
    y_inf_places = []
    for j, b in enumerate(B):
        others = [abs(b - u) for u in B if u is not b]
        r = min(others) * 0.35 if others else 1.0
        r = min(r, abs(x0 - b) * 0.5)
        r = max(r, 1e-6)
        u = (x0 - b) / abs(x0 - b)
        entry = b + r * u
        path = [x0, entry] + _circle(b, r, ncirc)[0:] + [entry, x0]
        # _circle starts and ends at b+r (angle 0); rotate so it starts at entry
        circ = [b + r * u * cmath.exp(2j * math.pi * t / ncirc) for t in range(ncirc + 1)]
        path = [x0, entry] + circ[1:] + [x0]
        try:
            ye, acc = T.transport(path, ys0, nsub)
            perm = T.match(ye, ys0)
        except RuntimeError as e:
            return {"error": "transport: %s" % e, "n_branch": len(B)}
        for k in range(dy):
            edges.append((j, k, perm[k], complex(acc[k])))
        info_loops.append({"b": [b.real, b.imag], "perm": perm})
        # classify the cycles over b_j: a cycle whose sheets stay finite is an
        # honest point of F_c (a ramification point); a cycle whose sheets blow
        # up is a PUNCTURE (a place with y = infinity over a root of lc_y f).
        # how many sheets run off to y = infinity over b?  exactly the drop in
        # the y-degree of f at x = b (b is then a root of lc_y f).
        cb = ycoef_desc(T.Ac, b)
        sc = max(abs(cb).max(), 1e-300)
        nb_inf = 0
        while nb_inf < len(cb) - 1 and abs(cb[nb_inf]) < 1e-10 * sc:
            nb_inf += 1
        blow_idx = set()
        if nb_inf > 0:
            ysm, _ = T.transport([x0, entry], ys0, nsub)
            blow_idx = set(int(t) for t in np.argsort(-np.abs(ysm))[:nb_inf])
        seen = set()
        for k in range(dy):
            if k in seen:
                continue
            cyc = [k]
            seen.add(k)
            m = perm[k]
            while m != k:
                cyc.append(m)
                seen.add(m)
                m = perm[m]
            blow = bool(blow_idx & set(cyc))
            tot = sum(acc[t] for t in cyc)
            if blow:
                y_inf_places.append({"over_x": [b.real, b.imag], "e": len(cyc),
                                     "residue": [(tot / (2j * math.pi)).real,
                                                 (tot / (2j * math.pi)).imag],
                                     "abs": abs(tot / (2j * math.pi))})
            else:
                finite_cycles += 1

    # ---- potential consistency (union-find with weights) --------------
    parent = list(range(dy))
    pot = [0.0 + 0j] * dy

    def find(a):
        root = a
        acc = 0.0 + 0j
        while parent[root] != root:
            acc += pot[root]
            root = parent[root]
        return root, acc

    periods = []
    for (j, k, kk, val) in edges:
        ra, pa = find(k)
        rb, pb = find(kk)
        # want u[kk] - u[k] = val ; u[k] = pa + U[ra], u[kk] = pb + U[rb]
        if ra == rb:
            periods.append(((j, k, kk), (pb - pa) - val))
        else:
            parent[rb] = ra
            pot[rb] = pa + val - pb

    ncomp = len({find(k)[0] for k in range(dy)})
    pv = [abs(p[1]) for p in periods]
    scale = max([abs(e[3]) for e in edges] + [1.0])

    # resolution-independent obstruction measure: the least-squares residual of
    # the potential system  u[sigma_j(k)] - u[k] = v_{j,k}.  It is zero exactly
    # when every period vanishes, and does not depend on which spanning tree
    # the union-find happened to build.
    Amat = np.zeros((len(edges), dy), dtype=np.complex128)
    rhs = np.zeros(len(edges), dtype=np.complex128)
    for t, (j, k, kk, val) in enumerate(edges):
        Amat[t, kk] += 1.0
        Amat[t, k] -= 1.0
        rhs[t] = val
    sol, _, _, _ = np.linalg.lstsq(Amat, rhs, rcond=None)
    ls_resid = float(np.linalg.norm(Amat.dot(sol) - rhs))

    # ---- monodromy at infinity + residues -----------------------------
    Rbig = max([abs(b) for b in B] + [1.0]) * 3.0 + 2.0
    inf = {"ok": False}
    try:
        u = x0 / abs(x0)
        big = [Rbig * u * cmath.exp(2j * math.pi * t / (4 * ncirc))
               for t in range(4 * ncirc + 1)]
        path = [x0, big[0]] + big[1:] + [x0]
        ysA = T.roots(big[0])
        yeA, accA = T.transport(path[1:-1], ysA, nsub)
        permA = T.match(yeA, ysA)
        # cycles of permA = places over x = infinity
        seen = set()
        res = []
        for k in range(dy):
            if k in seen:
                continue
            cyc = [k]
            seen.add(k)
            m = permA[k]
            while m != k:
                cyc.append(m)
                seen.add(m)
                m = permA[m]
            # the local loop around a place over x = infinity is the CLOCKWISE
            # circle in x, so the residue carries the opposite sign.
            tot = -sum(accA[t] for t in cyc)
            res.append({"cycle": cyc, "e": len(cyc),
                        "residue": [(tot / (2j * math.pi)).real,
                                    (tot / (2j * math.pi)).imag],
                        "abs": abs(tot / (2j * math.pi))})
        allres = [complex(*rr["residue"]) for rr in res] + \
                 [complex(*rr["residue"]) for rr in y_inf_places]
        inf = {"ok": True, "n_places_over_x_inf": len(res), "residues": res,
               "y_infinity_places": y_inf_places,
               "n_places_total": len(res) + len(y_inf_places),
               "sum_abs": abs(sum(allres)),
               "max_abs_residue": max([abs(z) for z in allres] + [0.0])}
    except RuntimeError as e:
        inf = {"ok": False, "err": str(e)}

    # Euler characteristic of F_c from the covering data:
    #   chi = dy*(1 - |B|) + #{cycles over the b_j that stay finite}
    # and chi = sum over components of (2 - 2g_i - n_i).
    chi = dy * (1 - len(B)) + finite_cycles
    npunct = inf.get("n_places_total") if inf.get("ok") else None
    gsum = None
    if npunct is not None:
        gsum = (2 * ncomp - npunct - chi)
        gsum = gsum // 2 if gsum % 2 == 0 else gsum / 2.0

    return {"dy": dy, "n_branch": len(B), "n_components": ncomp,
            "chi": chi, "n_punctures": npunct, "genus_sum": gsum,
            "n_independent_cycles_found": len(periods),
            "ls_residual": ls_resid,
            "max_period": max(pv) if pv else 0.0,
            "periods": [[p[0][0], p[0][1], p[0][2], p[1].real, p[1].imag]
                        for p in periods],
            "scale": scale, "infinity": inf, "x0": [x0.real, x0.imag]}


def screen_fibre_checked(P, c, tol=1e-6, verbose=False, **kw):
    """Run at two resolutions; the difference is the error estimate."""
    a = screen_fibre(P, c, nsub=kw.get("nsub", 6), ncirc=kw.get("ncirc", 64))
    if "error" in a:
        return a
    b = screen_fibre(P, c, nsub=2 * kw.get("nsub", 6), ncirc=2 * kw.get("ncirc", 64))
    if "error" in b:
        return b
    err = abs(a["ls_residual"] - b["ls_residual"])
    rel = b["ls_residual"] / b["scale"]
    verdict = "NONVANISHING" if rel > tol and err < 0.1 * b["ls_residual"] + 1e-12 \
        else ("VANISHING" if rel <= tol else "UNRESOLVED")
    b["err_ls_residual"] = err
    b["err_max_period"] = abs(a["max_period"] - b["max_period"])
    b["rel_ls_residual"] = rel
    b["verdict"] = verdict
    if b["infinity"].get("ok") and a["infinity"].get("ok"):
        b["infinity"]["sum_abs_lowres"] = a["infinity"]["sum_abs"]
    return b
