default(parisize, 1000000000);
read("sf_params.gp");
topol(v) = Pol(vector(#v, i, v[#v+1-i]), y);
E = topol(ELIM);
Dn = topol(DEN);
print("E irreducible: ", polisirreducible(E), " | deg: ", poldegree(E), " | real roots: ", polsturm(E));
print("denominator == E': ", Dn == deriv(E, y));
th = Mod(y, E);
Dv = subst(Dn, y, th);
val(i) = -subst(topol(eval(Str("PAR", i))), y, th)/(Dv*eval(Str("CST", i)));
p = vector(14, k, val(k-1));
r = vector(8, k, val(14+k-1));
Pw = x^14 + sum(k=1, 14, p[k]*x^(k-1));
Rw = x^9 + x^8 + sum(k=1, 8, r[k]*x^(k-1));
h = 2*deriv(Pw, x)*Rw*x - Pw*(Rw + 3*x*deriv(Rw, x));
hp = h - polcoef(h, 0, x);
print("[", if(hp == 0, "PASS", "FAIL"), "] h = 2P'Rw - P(R+3wR') exactly CONSTANT over K14");
h0 = polcoef(h, 0, x);
N = Pw^2 - x*Rw^3;
print("[", if(poldegree(N, x) == 5, "PASS", "FAIL"), "] miracle cancellation deg(P^2 - wR^3) = 5  (28 -> 5, 23-fold)");
n5 = polcoef(N, 5, x);
print("[", if(h0 + 23*n5 == 0, "PASS", "FAIL"), "] cross-epoch identity h0 = -23 n5");
print("[", if(h0 != 0, "PASS", "FAIL"), "] h0 != 0");
print("[", if(poldisc(Pw, x) != 0, "PASS", "FAIL"), "] P squarefree (14 order-2 points over 0)");
print("[", if(poldisc(Rw, x) != 0, "PASS", "FAIL"), "] R squarefree (9 order-3 points over inf)");
print("[", if(poldisc(N, x) != 0, "PASS", "FAIL"), "] N squarefree (5 simple points over 1)");
print("[", if(polresultant(Pw, Rw, x) != 0, "PASS", "FAIL"), "] gcd(P,R) = 1");
print("[", if(polresultant(Pw, N, x) != 0, "PASS", "FAIL"), "] gcd(P,N) = 1");
print("[", if(polresultant(Rw, N, x) != 0, "PASS", "FAIL"), "] gcd(R,N) = 1");
print("[", if(subst(Pw, x, 0) != 0 && subst(Rw, x, 0) != 0, "PASS", "FAIL"), "] P(0), R(0) != 0");
write("sf_PR_h0.txt", lift(h0));
for(k = 1, 14, write(Str("sf_PR_p", k-1, ".txt"), lift(p[k])));
for(k = 1, 8, write(Str("sf_PR_r", k-1, ".txt"), lift(r[k])));
write("sf_PR_E.txt", E);
print("EXPORTED. CERT DONE");
