default(parisize, 12000000000);
s = concat(readstr("/tmp/param_clean.txt"));
V = eval(s);
A = V[2][6][2];
d = A[1][1]; c = A[1][2];
print("stated degree     : ", d);
print("coefficient count : ", #c, "  => degree ", #c-1);
f = sum(i=1, #c, c[i]*x^(i-1));
f = f/content(f);
print("ELIMINANT degree  : ", poldegree(f));
print("squarefree        : ", issquarefree(f));
print("gcd(f,f') degree  : ", poldegree(gcd(f, deriv(f))));
print("coefficient size  : ", #digits(abs(polcoef(f, poldegree(f)))), " digits (leading)");
write("/home/user/jacobian_planar/wave1/edgeQ_eliminant.txt", f);
print("--- rational roots: each would be a candidate Q-point of the edge variety ---");
r = polrootsQ(f);
print("rational roots    : ", #r);
if(#r>0, print(r));
quit;
