default(parisize, 4000000000);
S = readstr("/home/user/jacobian_planar/campaign/audit_tracks/trackB_edgeQ.msolve.out");
s = concat(S);
V = eval(s);
print("top-level length : ", #V);
print("V[1] (dim)       : ", V[1]);
W = V[2];
print("V[2] length      : ", #W, "   W[1] = ", W[1]);
R = W[2];
print("RUR block length : ", #R);
E = R[1];
print("first entry len  : ", #E);
p = E[1];
print("eliminant coeff count : ", #p, "  => degree ", #p-1);
f = sum(i=1, #p, p[i]*x^(i-1));
f = f/content(f);
print("degree           : ", poldegree(f));
print("squarefree       : ", issquarefree(f));
print("--- rational roots (candidate Q-solutions) ---");
r = polrootsQ(f);
print("rational roots   : ", #r);
if(#r>0, print(r));
quit;
